name: 'Pull Request Comment'
author: 'Dave Schmitz'
description: 'Adds a pull request comment'

# Define your inputs here.
inputs:
  message_body:
    description: 'Pull request comment message body'
    required: true
    default: 'World'

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
